import json
import os
from typing import Dict, Any, List

class StellariumScriptGenerator:
    """
    Generates .ssc scripts for Stellarium based on enriched cultural data.
    """

    def __init__(self, enriched_library_path: str, output_dir: str):
        self.enriched_library_path = enriched_library_path
        self.output_dir = output_dir

    def load_data(self) -> Dict[str, Any]:
        with open(self.enriched_library_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def generate_scripts(self):
        data = self.load_data()
        
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

        for culture_id, culture_info in data.items():
            script_content = self._create_script_content(culture_id, culture_info)
            filename = os.path.join(self.output_dir, f"load_{culture_id}.ssc")
            
            with open(filename, "w", encoding="utf-8") as f:
                f.write(script_content)
            
            print(f"Generated script: {filename}")

    def _create_script_content(self, culture_id: str, info: Dict[str, Any]) -> str:
        """
        Creates the actual .ssc script content.
        Uses core.setSkyCulture() and potentially other commands.
        """
        lines = []
        lines.append(f'// Stellarium Script for Culture: {info.get("name", culture_id)}')
        lines.append('// Generated by Sky-Culture Engine')
        lines.append('')
        
        # Basic setup
        lines.append('core.clear("natural");')
        lines.append('core.setGuiVisible(true);')
        
        # Set Sky Culture
        # Note: Stellarium needs the culture ID to match folder name in skycultures
        lines.append(f'core.setSkyCulture("{culture_id}");')
        
        # Turn on constellations
        lines.append('ConstellationMgr.setFlagLines(true);')
        lines.append('ConstellationMgr.setFlagLabels(true);')
        lines.append('ConstellationMgr.setFlagArt(true);')
        
        # Date handling (if we had specific dates, we'd set them here)
        # For now, just a comment or default
        lines.append('// core.setDate("2000-01-01T00:00:00");')

        # Location (if region known, could set it, but keep default for now)
        
        lines.append('')
        lines.append('core.debug("Culture loaded: ' + culture_id + '");')
        
        return "\n".join(lines)

if __name__ == "__main__":
    base_dir = r"d:\Sky Cultures\sky_culture_engine"
    input_file = os.path.join(base_dir, "data", "enriched_cultural_library.json")
    output_scripts_dir = os.path.join(base_dir, "scripts")
    
    generator = StellariumScriptGenerator(input_file, output_scripts_dir)
    generator.generate_scripts()
